spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    initialization-mode: ALWAYS
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: hhz
    password: 123