spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sshelloworld?serverTimezone=GMT%2B8&amp&useSSL=false&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    data: "classpath:/init/data.sql"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
    ddl-auto: create-drop
